import { cssVarName, loadTokenSets, resolveAliases, tokenKey, writeFile } from "./token-utils.mjs";

const { lightFlat, darkFlat } = loadTokenSets();
const light = resolveAliases(lightFlat);
const dark = resolveAliases(darkFlat);

const cssLines = [
  "/* Generated by scripts/build-tokens.mjs. Do not edit manually. */",
  ":root {"
];

for (const [name, value] of Object.entries(light).sort()) {
  cssLines.push(`  ${cssVarName(name)}: ${value};`);
}

cssLines.push("}", "", "[data-theme=\"dark\"] {");

for (const [name, value] of Object.entries(dark).sort()) {
  if (light[name] !== value) cssLines.push(`  ${cssVarName(name)}: ${value};`);
}

cssLines.push("}", "");
writeFile("src/styles/tokens.css", `${cssLines.join("\n")}\n`);

function collect(prefix) {
  return Object.keys(light)
    .filter((name) => name.startsWith(prefix))
    .sort()
    .reduce((items, name) => {
      items[tokenKey(name)] = `var(${cssVarName(name)})`;
      return items;
    }, {});
}

function collectValues(prefix) {
  return Object.keys(light)
    .filter((name) => name.startsWith(prefix))
    .sort()
    .reduce((items, name) => {
      items[tokenKey(name)] = light[name];
      return items;
    }, {});
}

const config = `/* Generated by scripts/build-tokens.mjs. Do not edit manually. */
module.exports = {
  content: ["./.storybook/**/*.{svelte,ts,js}", "./src/**/*.{svelte,ts}", "./src/**/*.stories.{svelte,ts,js}", "./docs/**/*.md"],
  theme: {
    screens: ${JSON.stringify(collectValues("breakpoint."), null, 6)},
    extend: {
      colors: ${JSON.stringify(collect("color."), null, 6)},
      spacing: ${JSON.stringify(collect("spacing."), null, 6)},
      borderRadius: ${JSON.stringify(collect("radius."), null, 6)},
      boxShadow: ${JSON.stringify(collect("shadow."), null, 6)},
      fontFamily: {
        sans: "var(--font-family-sans)",
        numeric: "var(--font-family-numeric)"
      },
      fontSize: ${JSON.stringify(collect("font.size."), null, 6)},
      fontWeight: ${JSON.stringify(collect("font.weight."), null, 6)},
      lineHeight: ${JSON.stringify(collect("font.lineHeight."), null, 6)},
      transitionDuration: ${JSON.stringify(collect("motion.duration."), null, 6)},
      transitionTimingFunction: ${JSON.stringify(collect("motion.easing."), null, 6)}
    }
  },
  plugins: []
};
`;

writeFile("tailwind.config.cjs", config);
console.log("Generated src/styles/tokens.css and tailwind.config.cjs");
